---
groups:
  - name: certify-vsphere
    jobs:
      - bats-centos
      - bats-ubuntu
      - test-upgrade
      - certify-centos
      - certify-ubuntu

shared:
  - &prepare-director
    task: prepare-director
    tags: [vsphere-v5.1]
    file: pipelines/vsphere/tasks/prepare-director.yml
    params: &prepare-director-params
      BOSH_DIRECTOR_USERNAME:                 {{BOSH_DIRECTOR_USERNAME}}
      BOSH_DIRECTOR_PASSWORD:                 {{BOSH_DIRECTOR_PASSWORD}}
      BOSH_VSPHERE_VCENTER:                   {{VCENTER_IP}}
      BOSH_VSPHERE_VCENTER_USER:              {{VCENTER_USER}}
      BOSH_VSPHERE_VCENTER_PASSWORD:          {{VCENTER_PASSWORD}}
      BOSH_VSPHERE_VERSION:                   {{VSPHERE_VERSION}}
      BOSH_VSPHERE_VCENTER_DC:                {{VCENTER_DC}}
      BOSH_VSPHERE_VCENTER_CLUSTER:           {{VCENTER_CLUSTER}}
      BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
      BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}
      BOSH_VSPHERE_VCENTER_VM_FOLDER:         {{VCENTER_VM_FOLDER}}
      BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:   {{VCENTER_TEMPLATE_FOLDER}}
      BOSH_VSPHERE_VCENTER_DISK_PATH:         {{VCENTER_DISK_PATH}}
      SSLIP_IO_KEY:                           {{sslip_io_key}}

  - &deploy-director
    task: deploy-director
    tags: [vsphere-v5.1]
    file: pipelines/shared/tasks/deploy-director.yml

  - &prepare-bats
    task: prepare-bats
    tags: [vsphere-v5.1]
    file: pipelines/vsphere/tasks/prepare-bats.yml
    params: &prepare-bats-params
      BAT_VCAP_PASSWORD:      {{BAT_VCAP_PASSWORD}}
      BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
      BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

  - &run-bats
    task: run-bats
    tags: [vsphere-v5.1]
    file: pipelines/shared/tasks/run-bats.yml

  - &teardown
    task: teardown
    tags: [vsphere-v5.1]
    file: pipelines/shared/tasks/teardown.yml
    params:
      DEPLOYMENT_NAME: certification

jobs:
  - name: bats-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,   tags: [vsphere-v5.1], trigger: true}
        - {get: cpi-release,    tags: [vsphere-v5.1], trigger: true}
        - {get: stemcell,       tags: [vsphere-v5.1], trigger: true, resource: centos-stemcell}
        - {get: after-midnight, tags: [vsphere-v5.1], trigger: true}
        - {get: pipelines,      tags: [vsphere-v5.1], trigger: false}
        - {get: bosh-cli,       tags: [vsphere-v5.1], trigger: false}
        - {get: bats,           tags: [vsphere-v5.1], trigger: false}

      - {put: environment, tags: [vsphere-v5.1], params: {acquire: true}}

      - <<: *prepare-director

      - do:
          - <<: *deploy-director

          - <<: *prepare-bats
            params:
              <<: *prepare-bats-params
              STEMCELL_NAME: bosh-vsphere-esxi-centos-7-go_agent

          - <<: *run-bats

        ensure:
          do:
            - <<: *teardown

            - {put: environment, tags: [vsphere-v5.1], params: {release: environment}}

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,   tags: [vsphere-v5.1], trigger: true}
        - {get: cpi-release,    tags: [vsphere-v5.1], trigger: true}
        - {get: stemcell,       tags: [vsphere-v5.1], trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight, tags: [vsphere-v5.1], trigger: true}
        - {get: pipelines,      tags: [vsphere-v5.1], trigger: false}
        - {get: bosh-cli,       tags: [vsphere-v5.1], trigger: false}
        - {get: bats,           tags: [vsphere-v5.1], trigger: false}

      - {put: environment, tags: [vsphere-v5.1], params: {acquire: true}}

      - <<: *prepare-director

      - do:
          - <<: *deploy-director

          - <<: *prepare-bats
            params:
              <<: *prepare-bats-params
              STEMCELL_NAME: bosh-vsphere-esxi-ubuntu-trusty-go_agent

          - <<: *run-bats

        ensure:
          do:
            - <<: *teardown

            - {put: environment, tags: [vsphere-v5.1], params: {release: environment}}

  - name: test-upgrade
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,     tags: [vsphere-v5.1], trigger: true}
        - {get: cpi-release,      tags: [vsphere-v5.1], trigger: true}
        - {get: stemcell,         tags: [vsphere-v5.1], trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,   tags: [vsphere-v5.1], trigger: true}
        - {get: pipelines,        tags: [vsphere-v5.1], trigger: false}
        - {get: bosh-cli,         tags: [vsphere-v5.1], trigger: false}
        - {get: centos-stemcell,  tags: [vsphere-v5.1], trigger: false} # pass-through
        - {get: old-stemcell,     tags: [vsphere-v5.1], trigger: false}
        - {get: old-bosh-release, tags: [vsphere-v5.1], trigger: false}
        - {get: old-cpi-release,  tags: [vsphere-v5.1], trigger: false}

      - {put: environment, tags: [vsphere-v5.1], params: {acquire: true}}

      - <<: *prepare-director
        input_mapping:
          stemcell:     old-stemcell
          bosh-release: old-bosh-release
          cpi-release:  old-cpi-release
        params:
          <<: *prepare-director-params
          USE_REDIS:         true

      - do:
          - <<: *deploy-director
            input_mapping:
              stemcell:     old-stemcell
              bosh-release: old-bosh-release
              cpi-release:  old-cpi-release

          - task: prepare-deployment
            tags: [vsphere-v5.1]
            file: pipelines/vsphere/tasks/prepare-deployment.yml
            params:
              RELEASE_NAME:              certification
              DEPLOYMENT_NAME:           certification
              STEMCELL_NAME:             bosh-vsphere-esxi-ubuntu-trusty-go_agent
              BOSH_DIRECTOR_USERNAME:    {{BOSH_DIRECTOR_USERNAME}}
              BOSH_DIRECTOR_PASSWORD:    {{BOSH_DIRECTOR_PASSWORD}}
              BOSH_VSPHERE_VCENTER_VLAN: {{VCENTER_VLAN}}

          - task: create-deployment
            tags: [vsphere-v5.1]
            file: pipelines/vsphere/tasks/create-deployment.yml
            input_mapping:
              stemcell:                  old-stemcell
            params:
              BOSH_DIRECTOR_USERNAME:    {{BOSH_DIRECTOR_USERNAME}}
              BOSH_DIRECTOR_PASSWORD:    {{BOSH_DIRECTOR_PASSWORD}}
              RELEASE_NAME:              certification
              DEPLOYMENT_NAME:           certification

          - <<: *prepare-director

          - task: test-upgrade
            tags: [vsphere-v5.1]
            file: pipelines/shared/tasks/test-upgrade.yml
            input_mapping:
              old-director-state: director-state
              new-director-config: director-config
            output_mapping:
              new-director-state: director-state
            params:
              DEPLOYMENT_NAME:        certification

        ensure:
          do:
            - <<: *teardown

            - {put: environment, tags: [vsphere-v5.1], params: {release: environment}}

  - name: certify-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v5.1], trigger: true, passed: [bats-centos]}
        - {get: cpi-release,  tags: [vsphere-v5.1], trigger: true, passed: [bats-centos]}
        - {get: stemcell,     tags: [vsphere-v5.1], trigger: true, passed: [bats-centos, test-upgrade], resource: centos-stemcell}
        - {get: pipelines,    tags: [vsphere-v5.1], trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v5.1]
        params:
          CPI_RELEASE_NAME: bosh-vsphere-cpi
          STEMCELL_NAME:    bosh-vsphere-esxi-centos-7-go_agent

      - {put: receipt, tags: [vsphere-v5.1], params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v5.1], trigger: true, passed: [bats-ubuntu]}
        - {get: cpi-release,  tags: [vsphere-v5.1], trigger: true, passed: [bats-ubuntu]}
        - {get: stemcell,     tags: [vsphere-v5.1], trigger: true, passed: [bats-ubuntu, test-upgrade], resource: ubuntu-stemcell}
        - {get: pipelines,    tags: [vsphere-v5.1], trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v5.1]
        params:
          CPI_RELEASE_NAME: bosh-vsphere-cpi
          STEMCELL_NAME:    bosh-vsphere-esxi-ubuntu-trusty-go_agent

      - {put: receipt, tags: [vsphere-v5.1], params: {file: certification/*-receipt.json}}

resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM -0700
      stop: 2:00 AM -0700

  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vsphere-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent

  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1

  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-(\d+)-receipt\.json
      region_name: us-east-1

  - name: environment
    type: pool
    source:
      pool: vsphere-5.1
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}

  # upgrade resources
  - name: old-bosh-release
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: bosh-(229).tgz
      region_name: us-east-1

  - name: old-cpi-release
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: bosh-vsphere-cpi-release-(14).tgz
      region_name: us-east-1

  - name: old-stemcell
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: bosh-stemcell-(3143)-vsphere-esxi-ubuntu-trusty-go_agent.tgz
      region_name: us-east-1
